version: '3'

services:
  redis:
    container_name: redis
    image: 'redis'
    ports:
      - '7379:6379'

  sumosv:
    container_name: sumosv
    restart: always
    build:
      context: .
      dockerfile: ./sumosv/Dockerfile
    #ports: --> now hidden behind nginx
    #  - 5000:5000
    environment:
      - SUMO_USER=${sumo_user}
      - SUMO_PASS=${sumo_pass}
      - FLASK_APP=sumosv.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
      - FLASK_DEBUG=True
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SLACK_CONFIG_LOCATION=./config/slack_config.ini
    links:
      - redis
    depends_on:
      - redis

  canarybot:
    container_name: canarybot
    restart: always
    build:
      context: .
      dockerfile: ./canarybot/Dockerfile
    environment:
      - SLACK_BOT_TOKEN=${slack_token}
      - SLACK_CONFIG_LOCATION=./config/slack_config.ini
    links:
      - redis
    depends_on:
      - redis

  worker:
    container_name: worker
    restart: always
    build:
      context: .
      dockerfile: ./worker/Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - QUEUE_NAME=test
    links:
      - redis
    depends_on:
      - sumosv
      - canarybot
      - redis

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    links:
      - sumosv
    depends_on:
      - sumosv